class Type < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択してください' },
    { id: 2, name: 'アルテオン' },
    { id: 3, name: 'cross up!' },
    { id: 4, name: 'クロスゴルフ' },
    { id: 5, name: 'クロストゥーラン' },
    { id: 6, name: 'クロスポロ' },
    { id: 7, name: 'e-ゴルフ' },
    { id: 8, name: 'ゴルフ' },
    { id: 9, name: 'ゴルフヴァリアント' },
    { id: 10, name: 'ゴルフオールトラック' },
    { id: 11, name: 'ゴルフトゥーラン' },
    { id: 12, name: 'パサート' },
    { id: 13, name: 'パサートオールトラック' },
    { id: 14, name: 'パサートヴァリアント' },
    { id: 15, name: 'ポロ' },
    { id: 16, name: 'シャラン' },
    { id: 17, name: 'T-Cross' },
    { id: 18, name: 'T-Roc' },
    { id: 19, name: 'ザ・ビートル' },
    { id: 20, name: 'ティグアン' },
    { id: 21, name: 'A1' },
    { id: 22, name: 'A3' },
    { id: 23, name: 'A4' },
    { id: 24, name: 'A5' },
    { id: 25, name: 'A6' },
    { id: 26, name: 'A7' },
    { id: 27, name: 'A8' },
    { id: 28, name: 'Q2' },
    { id: 29, name: 'Q3' },
    { id: 30, name: 'Q5' },
    { id: 31, name: 'Q7' },
    { id: 32, name: 'Q8' },
    { id: 33, name: 'S1' },
    { id: 34, name: 'S3' },
    { id: 35, name: 'S4' },
    { id: 36, name: 'S5' },
    { id: 37, name: 'S6' },
    { id: 38, name: 'S7' },
    { id: 39, name: 'S8' },
    { id: 40, name: 'SQ2' },
    { id: 41, name: 'SQ5' },
    { id: 42, name: 'RS3' },
    { id: 43, name: 'RS4' },
    { id: 44, name: 'RS5' },
    { id: 45, name: 'RS6' },
    { id: 46, name: 'RS7' },
    { id: 47, name: 'RS Q3' },
    { id: 48, name: 'R8' },
    { id: 49, name: 'TT' },
    { id: 50, name: 'TT RS' },
    { id: 51, name: 'Aクラス' },
    { id: 52, name: 'Bクラス' },
    { id: 53, name: 'Cクラス' },
    { id: 54, name: 'Eクラス' },
    { id: 55, name: 'Gクラス' },
    { id: 56, name: 'Sクラス' },
    { id: 57, name: 'Vクラス' },
    { id: 58, name: 'CLA' },
    { id: 59, name: 'CLS' },
    { id: 60, name: 'GLA' },
    { id: 61, name: 'GLB' },
    { id: 62, name: 'GLC' },
    { id: 63, name: 'GLE' },
    { id: 64, name: 'GLS' },
    { id: 65, name: 'SL' },
    { id: 66, name: 'SLC' },
    { id: 67, name: 'ゲレンデヴァーゲン' },
    { id: 68, name: 'EQC' },
    { id: 69, name: '1シリーズ' },
    { id: 70, name: '2シリーズ' },
    { id: 71, name: '3シリーズ' },
    { id: 72, name: '4シリーズ' },
    { id: 73, name: '5シリーズ' },
    { id: 74, name: '6シリーズ' },
    { id: 75, name: '7シリーズ' },
    { id: 76, name: '8シリーズ' },
    { id: 77, name: 'X1' },
    { id: 78, name: 'X2' },
    { id: 79, name: 'X3' },
    { id: 80, name: 'X4' },
    { id: 81, name: 'X5' },
    { id: 82, name: 'X6' },
    { id: 83, name: 'X7' },
    { id: 84, name: 'X3 M' },
    { id: 85, name: 'X4 M' },
    { id: 86, name: 'X5 M' },
    { id: 87, name: 'X6 M' },
    { id: 88, name: 'M2' },
    { id: 89, name: 'M3' },
    { id: 90, name: 'M4' },
    { id: 91, name: 'M5' },
    { id: 92, name: 'M6' },
    { id: 93, name: 'M8' },
    { id: 94, name: 'Z4' },
    { id: 95, name: 'i3' },
    { id: 96, name: 'i8' },
    { id: 97, name: 'その他' }
  ]
end
